# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'content.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_contentWD(object):
    def setupUi(self, contentWD):
        contentWD.setObjectName(_fromUtf8("contentWD"))
        contentWD.resize(800, 513)
        self.horizontalLayout = QtGui.QHBoxLayout(contentWD)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(contentWD)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.skw_index = QtGui.QWidget()
        self.skw_index.setObjectName(_fromUtf8("skw_index"))
        self.gridLayout = QtGui.QGridLayout(self.skw_index)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(153, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.skw_index)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(152, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 220, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 227, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.skw_index)
        self.skw_history = QtGui.QWidget()
        self.skw_history.setObjectName(_fromUtf8("skw_history"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.skw_history)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.twd_history = QtGui.QTreeWidget(self.skw_history)
        self.twd_history.setStyleSheet(_fromUtf8(""))
        self.twd_history.setAlternatingRowColors(True)
        self.twd_history.setObjectName(_fromUtf8("twd_history"))
        self.verticalLayout_3.addWidget(self.twd_history)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.skw_history)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lbl_history_updatetime = QtGui.QLabel(self.skw_history)
        self.lbl_history_updatetime.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_history_updatetime.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_history_updatetime.setText(_fromUtf8(""))
        self.lbl_history_updatetime.setObjectName(_fromUtf8("lbl_history_updatetime"))
        self.horizontalLayout_2.addWidget(self.lbl_history_updatetime)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.skw_history)
        self.skw_send = QtGui.QWidget()
        self.skw_send.setObjectName(_fromUtf8("skw_send"))
        self.verticalLayout = QtGui.QVBoxLayout(self.skw_send)
        self.verticalLayout.setMargin(15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_payto = QtGui.QLabel(self.skw_send)
        self.lbl_payto.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_payto.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_payto.setObjectName(_fromUtf8("lbl_payto"))
        self.gridLayout_2.addWidget(self.lbl_payto, 0, 0, 1, 1)
        self.led_send_payto = QtGui.QLineEdit(self.skw_send)
        self.led_send_payto.setObjectName(_fromUtf8("led_send_payto"))
        self.gridLayout_2.addWidget(self.led_send_payto, 0, 2, 1, 1)
        self.lbl_amount = QtGui.QLabel(self.skw_send)
        self.lbl_amount.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_amount.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_amount.setObjectName(_fromUtf8("lbl_amount"))
        self.gridLayout_2.addWidget(self.lbl_amount, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.led_send_amount = QtGui.QLineEdit(self.skw_send)
        self.led_send_amount.setMinimumSize(QtCore.QSize(200, 0))
        self.led_send_amount.setMaximumSize(QtCore.QSize(200, 16777215))
        self.led_send_amount.setObjectName(_fromUtf8("led_send_amount"))
        self.horizontalLayout_6.addWidget(self.led_send_amount)
        self.btn_max_amount = QtGui.QPushButton(self.skw_send)
        self.btn_max_amount.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_max_amount.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_max_amount.setObjectName(_fromUtf8("btn_max_amount"))
        self.horizontalLayout_6.addWidget(self.btn_max_amount)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(12)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbl_password = QtGui.QLabel(self.skw_send)
        self.lbl_password.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_password.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_password.setObjectName(_fromUtf8("lbl_password"))
        self.gridLayout_3.addWidget(self.lbl_password, 0, 0, 1, 1)
        self.led_send_password = QtGui.QLineEdit(self.skw_send)
        self.led_send_password.setEchoMode(QtGui.QLineEdit.Password)
        self.led_send_password.setObjectName(_fromUtf8("led_send_password"))
        self.gridLayout_3.addWidget(self.led_send_password, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl_result = QtGui.QLabel(self.skw_send)
        self.lbl_result.setMinimumSize(QtCore.QSize(0, 40))
        self.lbl_result.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_result.setFont(font)
        self.lbl_result.setStyleSheet(_fromUtf8(""))
        self.lbl_result.setText(_fromUtf8(""))
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName(_fromUtf8("lbl_result"))
        self.horizontalLayout_7.addWidget(self.lbl_result)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(180, 0, -1, 20)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_clear = QtGui.QPushButton(self.skw_send)
        self.btn_clear.setMinimumSize(QtCore.QSize(106, 0))
        self.btn_clear.setMaximumSize(QtCore.QSize(106, 16777215))
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.horizontalLayout_3.addWidget(self.btn_clear)
        self.btn_preview = QtGui.QPushButton(self.skw_send)
        self.btn_preview.setMinimumSize(QtCore.QSize(106, 0))
        self.btn_preview.setMaximumSize(QtCore.QSize(106, 16777215))
        self.btn_preview.setObjectName(_fromUtf8("btn_preview"))
        self.horizontalLayout_3.addWidget(self.btn_preview)
        self.btn_send = QtGui.QPushButton(self.skw_send)
        self.btn_send.setMinimumSize(QtCore.QSize(106, 0))
        self.btn_send.setMaximumSize(QtCore.QSize(106, 16777215))
        self.btn_send.setDefault(True)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.horizontalLayout_3.addWidget(self.btn_send)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.skw_send)
        self.skw_receive = QtGui.QWidget()
        self.skw_receive.setObjectName(_fromUtf8("skw_receive"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.skw_receive)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_receive = QtGui.QHBoxLayout()
        self.horizontalLayout_receive.setContentsMargins(20, 20, 50, -1)
        self.horizontalLayout_receive.setObjectName(_fromUtf8("horizontalLayout_receive"))
        self.label_4 = QtGui.QLabel(self.skw_receive)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_receive.addWidget(self.label_4)
        self.led_receiving_address = QtGui.QLineEdit(self.skw_receive)
        self.led_receiving_address.setMinimumSize(QtCore.QSize(350, 0))
        self.led_receiving_address.setReadOnly(True)
        self.led_receiving_address.setObjectName(_fromUtf8("led_receiving_address"))
        self.horizontalLayout_receive.addWidget(self.led_receiving_address)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_receive.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_receive)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.skw_receive)
        self.skw_addresses = QtGui.QWidget()
        self.skw_addresses.setStyleSheet(_fromUtf8("border:0px;"))
        self.skw_addresses.setObjectName(_fromUtf8("skw_addresses"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.skw_addresses)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 2, 10, 2)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_filter = QtGui.QLabel(self.skw_addresses)
        self.lbl_filter.setObjectName(_fromUtf8("lbl_filter"))
        self.horizontalLayout_8.addWidget(self.lbl_filter)
        self.cmb_receiving_change = QtGui.QComboBox(self.skw_addresses)
        self.cmb_receiving_change.setObjectName(_fromUtf8("cmb_receiving_change"))
        self.cmb_receiving_change.addItem(_fromUtf8(""))
        self.cmb_receiving_change.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cmb_receiving_change)
        self.cmb_all = QtGui.QComboBox(self.skw_addresses)
        self.cmb_all.setObjectName(_fromUtf8("cmb_all"))
        self.cmb_all.addItem(_fromUtf8(""))
        self.cmb_all.addItem(_fromUtf8(""))
        self.cmb_all.addItem(_fromUtf8(""))
        self.cmb_all.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cmb_all)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.label_2 = QtGui.QLabel(self.skw_addresses)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lbl_address_updatetime = QtGui.QLabel(self.skw_addresses)
        self.lbl_address_updatetime.setText(_fromUtf8(""))
        self.lbl_address_updatetime.setObjectName(_fromUtf8("lbl_address_updatetime"))
        self.horizontalLayout_8.addWidget(self.lbl_address_updatetime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.twd_addresses = QtGui.QTreeWidget(self.skw_addresses)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.twd_addresses.setFont(font)
        self.twd_addresses.setAlternatingRowColors(True)
        self.twd_addresses.setObjectName(_fromUtf8("twd_addresses"))
        self.verticalLayout_2.addWidget(self.twd_addresses)
        self.stackedWidget.addWidget(self.skw_addresses)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(contentWD)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(contentWD)

    def retranslateUi(self, contentWD):
        contentWD.setWindowTitle(_translate("contentWD", "Form", None))
        self.label.setText(_translate("contentWD", "Welcome to use the uwallet!", None))
        self.twd_history.setSortingEnabled(True)
        self.twd_history.headerItem().setText(0, _translate("contentWD", "Date", None))
        self.twd_history.headerItem().setText(1, _translate("contentWD", "Amount", None))
        self.twd_history.headerItem().setText(2, _translate("contentWD", "Fee", None))
        self.label_3.setText(_translate("contentWD", "update:  ", None))
        self.lbl_payto.setText(_translate("contentWD", "Pay to", None))
        self.lbl_amount.setText(_translate("contentWD", "Amount", None))
        self.btn_max_amount.setText(_translate("contentWD", "Max", None))
        self.lbl_password.setText(_translate("contentWD", "password", None))
        self.led_send_password.setPlaceholderText(_translate("contentWD", "Enter your wallet password", None))
        self.btn_clear.setText(_translate("contentWD", "Clear", None))
        self.btn_preview.setText(_translate("contentWD", "Preview", None))
        self.btn_send.setText(_translate("contentWD", "Send", None))
        self.label_4.setText(_translate("contentWD", "Receiving address: ", None))
        self.lbl_filter.setText(_translate("contentWD", "Filter : ", None))
        self.cmb_receiving_change.setItemText(0, _translate("contentWD", "Receiving", None))
        self.cmb_receiving_change.setItemText(1, _translate("contentWD", "Change", None))
        self.cmb_all.setItemText(0, _translate("contentWD", "All", None))
        self.cmb_all.setItemText(1, _translate("contentWD", "Unused", None))
        self.cmb_all.setItemText(2, _translate("contentWD", "Funded", None))
        self.cmb_all.setItemText(3, _translate("contentWD", "Frozen", None))
        self.label_2.setText(_translate("contentWD", "update: ", None))
        self.twd_addresses.setSortingEnabled(True)
        self.twd_addresses.headerItem().setText(0, _translate("contentWD", "Address", None))
        self.twd_addresses.headerItem().setText(1, _translate("contentWD", "Balance", None))

