# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_titleWD(object):
    def setupUi(self, titleWD):
        titleWD.setObjectName(_fromUtf8("titleWD"))
        titleWD.resize(898, 87)
        titleWD.setMinimumSize(QtCore.QSize(0, 87))
        titleWD.setMaximumSize(QtCore.QSize(16777215, 87))
        self.horizontalLayout = QtGui.QHBoxLayout(titleWD)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 3, -1, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_icon = QtGui.QLabel(titleWD)
        self.lbl_icon.setText(_fromUtf8(""))
        self.lbl_icon.setScaledContents(True)
        self.lbl_icon.setObjectName(_fromUtf8("lbl_icon"))
        self.horizontalLayout_2.addWidget(self.lbl_icon)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, -1, 0, 3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl_balance_title = QtGui.QLabel(titleWD)
        self.lbl_balance_title.setObjectName(_fromUtf8("lbl_balance_title"))
        self.horizontalLayout_7.addWidget(self.lbl_balance_title)
        self.lbl_balance = QtGui.QLabel(titleWD)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lbl_balance.setFont(font)
        self.lbl_balance.setAccessibleDescription(_fromUtf8(""))
        self.lbl_balance.setText(_fromUtf8(""))
        self.lbl_balance.setObjectName(_fromUtf8("lbl_balance"))

        self.horizontalLayout_7.addWidget(self.lbl_balance)

        self.lbl_balance_unit = QtGui.QLabel(titleWD)
        self.lbl_balance_unit.setObjectName(_fromUtf8("lbl_balance_unit"))
        self.horizontalLayout_7.addWidget(self.lbl_balance_unit)

        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.btn_file = QtGui.QPushButton(titleWD)
        self.btn_file.setFlat(True)
        self.btn_file.setObjectName(_fromUtf8("btn_file"))
        self.horizontalLayout_3.addWidget(self.btn_file)
        self.btn_wallet = QtGui.QPushButton(titleWD)
        self.btn_wallet.setFlat(True)
        self.btn_wallet.setObjectName(_fromUtf8("btn_wallet"))
        self.horizontalLayout_3.addWidget(self.btn_wallet)
        self.btn_view = QtGui.QPushButton(titleWD)
        self.btn_view.setFlat(True)
        self.btn_view.setObjectName(_fromUtf8("btn_view"))
        self.horizontalLayout_3.addWidget(self.btn_view)
        self.btn_tools = QtGui.QPushButton(titleWD)
        self.btn_tools.setFlat(True)
        self.btn_tools.setObjectName(_fromUtf8("btn_tools"))
        self.horizontalLayout_3.addWidget(self.btn_tools)
        self.btn_help = QtGui.QPushButton(titleWD)
        self.btn_help.setFlat(True)
        self.btn_help.setObjectName(_fromUtf8("btn_help"))
        self.horizontalLayout_3.addWidget(self.btn_help)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 8, -1, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(13)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tbt_history = QtGui.QToolButton(titleWD)
        self.tbt_history.setMinimumSize(QtCore.QSize(61, 0))
        self.tbt_history.setMaximumSize(QtCore.QSize(61, 16777215))
        self.tbt_history.setIconSize(QtCore.QSize(20, 20))
        self.tbt_history.setCheckable(True)
        self.tbt_history.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbt_history.setAutoRaise(True)
        self.tbt_history.setObjectName(_fromUtf8("tbt_history"))
        self.horizontalLayout_4.addWidget(self.tbt_history)
        self.tbt_send = QtGui.QToolButton(titleWD)
        self.tbt_send.setMinimumSize(QtCore.QSize(61, 0))
        self.tbt_send.setMaximumSize(QtCore.QSize(61, 16777215))
        self.tbt_send.setIconSize(QtCore.QSize(20, 20))
        self.tbt_send.setCheckable(True)
        self.tbt_send.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbt_send.setAutoRaise(True)
        self.tbt_send.setObjectName(_fromUtf8("tbt_send"))
        self.horizontalLayout_4.addWidget(self.tbt_send)
        self.tbt_receive = QtGui.QToolButton(titleWD)
        self.tbt_receive.setMinimumSize(QtCore.QSize(61, 0))
        self.tbt_receive.setMaximumSize(QtCore.QSize(61, 16777215))
        self.tbt_receive.setIconSize(QtCore.QSize(20, 20))
        self.tbt_receive.setCheckable(True)
        self.tbt_receive.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbt_receive.setAutoRaise(True)
        self.tbt_receive.setObjectName(_fromUtf8("tbt_receive"))
        self.horizontalLayout_4.addWidget(self.tbt_receive)
        self.tbt_addresses = QtGui.QToolButton(titleWD)
        self.tbt_addresses.setIconSize(QtCore.QSize(20, 20))
        self.tbt_addresses.setCheckable(True)
        self.tbt_addresses.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbt_addresses.setAutoRaise(True)
        self.tbt_addresses.setObjectName(_fromUtf8("tbt_addresses"))
        self.horizontalLayout_4.addWidget(self.tbt_addresses)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 8, 13, 5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.btn_min = QtGui.QPushButton(titleWD)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 24))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 24))
        self.btn_min.setText(_fromUtf8(""))
        self.btn_min.setObjectName(_fromUtf8("btn_min"))
        self.horizontalLayout_5.addWidget(self.btn_min)
        self.btn_max = QtGui.QPushButton(titleWD)
        self.btn_max.setMinimumSize(QtCore.QSize(36, 24))
        self.btn_max.setMaximumSize(QtCore.QSize(36, 24))
        self.btn_max.setText(_fromUtf8(""))
        self.btn_max.setObjectName(_fromUtf8("btn_max"))
        self.horizontalLayout_5.addWidget(self.btn_max)
        self.btn_close = QtGui.QPushButton(titleWD)
        self.btn_close.setMinimumSize(QtCore.QSize(36, 24))
        self.btn_close.setMaximumSize(QtCore.QSize(36, 24))
        self.btn_close.setText(_fromUtf8(""))
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_6.setSpacing(14)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.btn_password = QtGui.QPushButton(titleWD)
        self.btn_password.setMinimumSize(QtCore.QSize(15, 17))
        self.btn_password.setMaximumSize(QtCore.QSize(15, 17))
        self.btn_password.setStyleSheet(_fromUtf8("QToolButton:hover{\n"
"border:10px;\n"
"}  "))
        self.btn_password.setText(_fromUtf8(""))
        self.btn_password.setCheckable(True)
        self.btn_password.setObjectName(_fromUtf8("btn_password"))
        self.btn_password.setToolTip(_translate("titleWD", "Password", None) + '(Ctrl+P)')
        self.btn_password.setShortcut('Ctrl+P')
        self.horizontalLayout_6.addWidget(self.btn_password)
        self.btn_setting = QtGui.QPushButton(titleWD)
        self.btn_setting.setMinimumSize(QtCore.QSize(17, 17))
        self.btn_setting.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_setting.setText(_fromUtf8(""))
        self.btn_setting.setObjectName(_fromUtf8("btn_setting"))
        self.btn_setting.setShortcut('Ctrl+S')
        self.btn_setting.setToolTip(_translate("titleWD", "Setting", None)+ '(Ctrl+S)')
        self.horizontalLayout_6.addWidget(self.btn_setting)
        self.btn_seed = QtGui.QPushButton(titleWD)
        self.btn_seed.setMinimumSize(QtCore.QSize(17, 17))
        self.btn_seed.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_seed.setText(_fromUtf8(""))
        self.btn_seed.setObjectName(_fromUtf8("btn_seed"))
        self.btn_seed.setShortcut('Ctrl+Z')
        self.btn_seed.setToolTip(_translate("titleWD", "Seed", None)+ '(Ctrl+Z)')
        self.horizontalLayout_6.addWidget(self.btn_seed)
        self.btn_network = QtGui.QPushButton(titleWD)
        self.btn_network.setMinimumSize(QtCore.QSize(17, 17))
        self.btn_network.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_network.setText(_fromUtf8(""))
        self.btn_network.setToolTip(_translate("titleWD", "Network Status", None))
        self.btn_network.setObjectName(_fromUtf8("btn_network"))
        self.horizontalLayout_6.addWidget(self.btn_network)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(titleWD)
        QtCore.QMetaObject.connectSlotsByName(titleWD)

    def retranslateUi(self, titleWD):
        titleWD.setWindowTitle(_translate("titleWD", "Form", None))
        self.lbl_balance_title.setText(_translate("titleWD", "Balance: ", None))
        self.lbl_balance_unit.setText(_translate("titleWD", " UT", None))
        self.btn_file.setText(_translate("titleWD", "&File", None))
        self.btn_wallet.setText(_translate("titleWD", "&Wallet", None))
        self.btn_view.setText(_translate("titleWD", "&View", None))
        self.btn_tools.setText(_translate("titleWD", "&Tools", None))
        self.btn_help.setText(_translate("titleWD", "Help", None))
        self.tbt_history.setText(_translate("titleWD", "History", None))
        self.tbt_send.setText(_translate("titleWD", "Send", None))
        self.tbt_receive.setText(_translate("titleWD", "Receive", None))
        self.tbt_addresses.setText(_translate("titleWD", "Addresses", None))

